### ISSUE TITLE
How to evaluate the trained model?

### ISSUE THREAD

**Issue by zwy1996** [sthalles/SimCLR#10]

**Comment by zwy1996** [comment]
Hello,

Thanks for your nice work! When I used your code, I found that I can not download the pre-trained model, So the code was trained from scratch, could you offer the pre-trained model ? 

The second question was that how to evaluate the model.

Thank you very much!

**Comment by here101** [comment]
I have the same question,please how to evaluate the model.
I don't watch the evaluation in the code.
