### ISSUE TITLE
Why cos_sim after L2 norm?

### ISSUE THREAD

**Issue by BoPang1996** [sthalles/SimCLR#14]
Hi, This code is really useful for me. Thanks!
But I got a question about the NT-Xent loss. I noticed that you use L2 norm on z and then use cos_similarity after that. But cos_similarity already contain the function of l2 norm. Why use L2 norm first?

**Comment by nzw0301** [comment]
@BoPang1996 I thunk you are right. In this repo with default config parameters, `z` is normalized twice. So, we may set `False` to [this config parameter](https://github.com/sthalles/SimCLR/blob/e8a690ae4f4359528cfba6f270a9226e3733b7fa/config.yaml#L21) or remove the first normalization part on yours to make the training.

**Comment by sthalles** [comment]
Hello guys, that is a general message to say that I have refactored the whole project. I believe the project is much easier to understand now. Please have a look at the new impl and free to submit PR if you find any bugs. Thanks.
