### ISSUE TITLE
GPU utilization rate is low

### ISSUE THREAD

**Issue by LiJunnan1992** [sthalles/SimCLR#15]
Hi, thanks for the code!

When I tried to run it on single GPU (v-100), the utilizaiton rate is very low (~0-10%) even if I increase num_worker. Would you know why this happens and how to solve it? Thanks!

**Comment by JosephElHachem** [comment]
I am having the same observation. I am tempted to say that the most time consuming operations are generating the data augmentations. I haven't done the measurements yet though.

**Comment by sthalles** [comment]
Hello guys, that is a general message to say that I have refactored the whole project. I believe the project is much easier to understand now. Please have a look at the new impl and free to submit PR if you find any bugs. Thanks.
