### ISSUE TITLE
Run experiments on ImageNet

### ISSUE THREAD

**Issue by Abyssaledge** [sthalles/SimCLR#2]
Hi,
Thanks for your nice work. 
I am planning to run SimCLR on ImageNet dataset.  I wonder if I need to adjust the structure of network or add some tricks.  For example increasing the dimension of output used to calculating losses, which in your code is 64.  Or directly change the dataset to ImageNet and keep other configuration the same?
I'll appreciate any advice.

**Comment by Jessejx** [comment]
HI, have you finished it? I am planning to SimCLR on ImageNet dataset too.

**Comment by sthalles** [comment]
Hello guys, that is a general message to say that I have refactored the whole project. I believe the project is much easier to understand now. Please have a look at the new impl and free to submit PR if you find any bugs. Thanks.
