### ISSUE TITLE
What is the proper range of  NT xent loss when the network converges?

### ISSUE THREAD

**Issue by ckLibra** [sthalles/SimCLR#21]
After 80 epoch,my nt xent loss is about 5.I am not sure whether the network has learnt well.

**Comment by sthalles** [comment]
Hello guys, that is a general message to say that I have refactored the whole project. Please I a look at the new impl and free to submit PR if you find any bugs. Thanks.

**Comment by muyuuuu** [comment]
> After 80 epoch,my nt xent loss is about 5.I am not sure whether the network has learnt well.

I'm also meeting this problem, is it normal ? or how do you fix it?
