### ISSUE TITLE
Permission Denied with the model download link 

### ISSUE THREAD

**Issue by handworker** [sthalles/SimCLR#3]
Hi sthalles,
Thanks for your great implementation. When I run your linear_feature_eval.ipynb, there is one error about the model download link, which is: 
Permission denied: https://drive.google.com/uc?id=1LjuZ1RmhotrnugprRQc2Exk0EbQHMJhL
Maybe you need to change permission over 'Anyone with the link'?
unzip:  cannot find or open Mar14_05-52-52_thallessilva, Mar14_05-52-52_thallessilva.zip or Mar14_05-52-52_thallessilva.ZIP.
Could you change the link download permission? Thanks a lot.

**Comment by Yukun4119** [comment]
the same problem : (

**Comment by sthalles** [comment]
That has been fixed. Thanks.
