### ISSUE TITLE
Is it something wrong with the training model for CIFAR-10 experiments?

### ISSUE THREAD

**Issue by timqqt** [sthalles/SimCLR#34]
Hi,

I find that the ResNet20 model for CIFAR-10 experiments is not fully correct. The head conv structure should be modified (stride=1 and no pooling,) because the image size of CIFAR-10 is very small.

**Comment by lim0606** [comment]
For experiments `image_size <= 32`, I'm guessing you need to modify initial `conv1` and `maxpool`  layers following https://github.com/google-research/simclr/blob/3ad6700c1b139ee18e43f73546b7263a710de699/tf2/resnet.py#L551

```
model = models.resnet50(pretrained=False, num_classes=1) 
model.conv1 = nn.Conv2d(3, 64, kernel_size=3, stride=1, padding=1, bias=False)
model.maxpool = nn.Identity()
```

**Comment by timqqt** [comment]
Thanks. I see.


***********************************

Fanjie Kong

Ph.D. Student in Machine Learning

Electrical and Computer Engineering Department

Duke University

Durham, NC, 27708

Email: ***@***.***

LinkedIn: https://www.linkedin.com/in/fanjie-kong-9330a6196/

***********************************

________________________________
