### ISSUE TITLE
About  loss function

### ISSUE THREAD

**Issue by leeh43** [sthalles/SimCLR#9]
Hi,

Thank you for the great work and I am trying to use your code in 3D patches. I separately input two paired datasets, which contain the domain difference and didn't use the data augmentation. I have extracted the representation using an encoder. However, the contrastive loss calculation is zero. Is there any steps that I haven't done to run the code successfully?

Thanks a lot!

**Comment by sthalles** [comment]
Hello guys, that is a general message to say that I have refactored the whole project. I believe the project is much easier to understand now. Please have a look at the new impl and free to submit PR if you find any bugs. Thanks.
